[tools]
bun = "1.3.14"

[tasks.bun-install]
run = 'bun install --frozen-lockfile'

[tasks.pi-install]
run = 'curl -fsSL https://pi.dev/install.sh | sh'

[tasks.playwright-install]
run = [
  'sudo mise exec -- bunx playwright install-deps',
  'bunx playwright install'
]

[tasks.bootstrap]
depends = ['bun-install', 'pi-install', 'playwright-install']
