[tools]
node = "26"

[tasks.npm-install]
run = 'npm install'

[tasks.pi-install]
run = 'curl -fsSL https://pi.dev/install.sh | sh'

[tasks.playwright-install]
run = [
  'sudo mise exec -- npx playwright install-deps',
  'npx playwright install'
]

[tasks.bootstrap]
depends = ['npm-install', 'pi-install', 'playwright-install']
