import { readdir } from 'node:fs/promises';
import { extname, join, relative, sep } from 'node:path';

const root = join(import.meta.dirname, '..', 'build', 'client');
const output = join(import.meta.dirname, '..', 'src', 'server', 'embedded-assets.generated.ts');
const contentTypes: Record<string, string> = {
	'.html': 'text/html; charset=utf-8',
	'.js': 'text/javascript; charset=utf-8',
	'.css': 'text/css; charset=utf-8',
	'.png': 'image/png',
	'.svg': 'image/svg+xml',
	'.ico': 'image/x-icon',
	'.webp': 'image/webp',
	'.woff2': 'font/woff2'
};

async function files(directory: string): Promise<string[]> {
	const entries = await readdir(directory, { withFileTypes: true });
	const nested = await Promise.all(
		entries.map((entry) => {
			const path = join(directory, entry.name);
			return entry.isDirectory() ? files(path) : [path];
		})
	);
	return nested.flat().sort();
}

const assets: Record<string, { contentType: string; base64: string }> = {};
for (const path of await files(root)) {
	if (path.endsWith('.map')) continue;
	const route = '/' + relative(root, path).split(sep).join('/');
	const bytes = new Uint8Array(await Bun.file(path).arrayBuffer());
	assets[route] = {
		contentType: contentTypes[extname(path)] ?? 'application/octet-stream',
		base64: Buffer.from(bytes).toString('base64')
	};
}
await Bun.write(
	output,
	`// Generated by scripts/embed-client.ts. Do not edit.\nexport const embeddedAssets = ${JSON.stringify(assets)} as const;\n`
);
console.log(`Embedded ${Object.keys(assets).length} client assets.`);
